name: Docker Image CI

on:
  release:
    types:
    - published # 当发布新的 release 时触发
  push:
    branches:
    - build_image # 在推送到 build_image 分支时触发构建

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: "cuda:12.4.1-runtime-ubuntu20.04-uv" # 这里用于设置镜像名称

    steps:
    # 检出代码
    - name: Checkout code
      uses: actions/checkout@v3
    # 登录 Docker Hub
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    # 构建 Docker 镜像
    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_TAG }} -f Dockerfile .
    # 推送镜像到 Docker Hub
    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_TAG }}
