name: Docker Image CI

on:
  push:
    branches:
    - build_postgres-vector-age # 在推送到 build_postgres-vector-age 分支时触发构建

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: "postgres:pg17-vector0.8.1-age1.6.0" # 这里用于设置镜像名称

    steps:
    # 检出代码
    - name: Checkout code
      uses: actions/checkout@v3
    # 登录 Docker Hub
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    # 构建 Docker 镜像
    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_TAG }} ./postgres-vector-age
    # 推送镜像到 Docker Hub
    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_TAG }}
